# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: '3.7'

services:
  greengrass:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aws-iot-greengrass
    image: aarch64/aws-iot-greengrass:RELEASE_VERSION
    ports:
      - "8883:8883"
    env_file: ../.env
    volumes: 
     - ../greengrass-v2-credentials/credentials:/root/.aws/:ro 
